### ISSUE TITLE
no issues haha

### ISSUE THREAD

**Issue by CaspaX** [Schuh1337/Discord-MultiTool#10]
i am Caspa haha
Chapa gir. Master!
![Piada](https://github.com/user-attachments/assets/9844008a-8a10-4782-aa90-c06807b994a1)

**Comment by Schuh1337** [comment]
?

**Comment by CaspaX** [comment]
> ?
nothing bro just idk didn't had nothing to do btw do you have a discord server hah?

**Comment by Schuh1337** [comment]
i don't have a discord server
